export const artigos = [
  { slug: 'suco-de-abacaxi-natural', titulo: 'Como fazer o melhor suco de abacaxi natural' },
  { slug: 'receita-de-bolo-de-abacaxi', titulo: 'Receita de bolo de abacaxi fofinho' },
  { slug: 'beneficios-do-abacaxi', titulo: 'Os incríveis benefícios do abacaxi para a saúde' },
  { slug: 'abacaxi-na-dieta', titulo: 'Como incluir o abacaxi na sua dieta' },
  { slug: 'abacaxi-grelhado', titulo: 'Abacaxi grelhado: uma sobremesa saudável' },
  { slug: 'geleia-de-abacaxi', titulo: 'Como fazer geleia de abacaxi caseira' },
  { slug: 'abacaxi-com-hortela', titulo: 'Suco de abacaxi com hortelã: refrescante' },
  { slug: 'abacaxi-em-calda', titulo: 'Abacaxi em calda: receita tradicional' },
  { slug: 'como-escolher-abacaxi', titulo: 'Dicas para escolher um abacaxi maduro' },
  { slug: 'abacaxi-no-churrasco', titulo: 'Abacaxi no churrasco: o segredo do sucesso' },
  { slug: 'abacaxi-com-canela', titulo: 'Abacaxi com canela: uma combinação perfeita' },
  { slug: 'sorvete-de-abacaxi', titulo: 'Sorvete de abacaxi caseiro' },
  { slug: 'abacaxi-na-salada', titulo: 'Salada com abacaxi: sabor tropical' },
  { slug: 'abacaxi-assado', titulo: 'Abacaxi assado no forno' },
  { slug: 'abacaxi-e-digestao', titulo: 'Abacaxi e digestão: o que a ciência diz' },
  { slug: 'abacaxi-para-emagrecer', titulo: 'Abacaxi ajuda a emagrecer?' },
  { slug: 'abacaxi-na-culinaria', titulo: 'O uso do abacaxi na culinária mundial' },
  { slug: 'abacaxi-e-vitamina-c', titulo: 'Abacaxi: uma fonte rica em vitamina C' },
  { slug: 'abacaxi-e-bromelina', titulo: 'O poder da bromelina no abacaxi' },
  { slug: 'abacaxi-na-decoracao', titulo: 'Abacaxi na decoração de festas' },
  { slug: 'abacaxi-em-drinks', titulo: 'Drinks refrescantes com abacaxi' },
  { slug: 'abacaxi-com-coco', titulo: 'Abacaxi com coco: sabor tropical' },
  { slug: 'abacaxi-na-pizza', titulo: 'Pizza de abacaxi: ame ou odeie' },
  { slug: 'abacaxi-na-confeitaria', titulo: 'Abacaxi na confeitaria: dicas' },
  { slug: 'abacaxi-e-pele', titulo: 'Abacaxi e seus benefícios para a pele' },
  { slug: 'abacaxi-e-cabelo', titulo: 'Abacaxi para fortalecer o cabelo' },
  { slug: 'abacaxi-na-historia', titulo: 'A história do abacaxi' },
  { slug: 'abacaxi-no-mundo', titulo: 'Produção mundial de abacaxi' },
  { slug: 'tipos-de-abacaxi', titulo: 'Conheça os principais tipos de abacaxi' },
  { slug: 'abacaxi-perola', titulo: 'Tudo sobre o abacaxi pérola' },
  { slug: 'abacaxi-hawaii', titulo: 'O famoso abacaxi havaiano' },
  { slug: 'abacaxi-smoothie', titulo: 'Smoothie de abacaxi' },
  { slug: 'abacaxi-com-iogurte', titulo: 'Abacaxi com iogurte: lanche saudável' },
  { slug: 'abacaxi-e-diabetes', titulo: 'Abacaxi e diabetes: cuidados' },
  { slug: 'abacaxi-e-pressao', titulo: 'Abacaxi ajuda na pressão arterial?' },
  { slug: 'abacaxi-na-gravidez', titulo: 'Abacaxi na gravidez: pode comer?' },
  { slug: 'abacaxi-para-bebes', titulo: 'Abacaxi para bebês: quando oferecer?' },
  { slug: 'abacaxi-e-inflamacao', titulo: 'Abacaxi contra inflamações' },
  { slug: 'abacaxi-e-imunidade', titulo: 'Abacaxi para aumentar a imunidade' },
  { slug: 'abacaxi-na-festa', titulo: 'Ideias de festas com tema abacaxi' },
  { slug: 'abacaxi-e-detox', titulo: 'Suco detox de abacaxi' },
  { slug: 'abacaxi-e-fibra', titulo: 'Abacaxi e o funcionamento do intestino' },
  { slug: 'abacaxi-e-potassio', titulo: 'Abacaxi e a importância do potássio' },
  { slug: 'abacaxi-e-antioxidante', titulo: 'Abacaxi: um poderoso antioxidante' },
  { slug: 'abacaxi-e-energia', titulo: 'Abacaxi para dar energia' },
  { slug: 'abacaxi-na-cozinha', titulo: 'Dicas para usar abacaxi na cozinha' },
  { slug: 'abacaxi-e-conservacao', titulo: 'Como conservar abacaxi por mais tempo' },
  { slug: 'abacaxi-e-congelamento', titulo: 'Como congelar abacaxi corretamente' },
  { slug: 'abacaxi-e-descascar', titulo: 'Como descascar abacaxi sem desperdício' },
  { slug: 'abacaxi-e-cortar', titulo: 'Como cortar abacaxi em cubos' },
  { slug: 'abacaxi-e-fatiar', titulo: 'Como fatiar abacaxi' },
  { slug: 'abacaxi-e-suco-concentrado', titulo: 'Como fazer suco concentrado de abacaxi' },
  { slug: 'abacaxi-e-doce', titulo: 'Doce de abacaxi simples' },
  { slug: 'abacaxi-e-mousse', titulo: 'Mousse de abacaxi' },
  { slug: 'abacaxi-e-pavê', titulo: 'Pavê de abacaxi' },
  { slug: 'abacaxi-e-torta', titulo: 'Torta de abacaxi' },
  { slug: 'abacaxi-e-bolo-gelado', titulo: 'Bolo gelado de abacaxi' },
  { slug: 'abacaxi-e-salada-de-frutas', titulo: 'Salada de frutas com abacaxi' },
  { slug: 'abacaxi-e-espetinho', titulo: 'Espetinho de abacaxi' },
  { slug: 'abacaxi-e-molho', titulo: 'Molho de abacaxi para carnes' },
  { slug: 'abacaxi-e-chutney', titulo: 'Chutney de abacaxi' },
  { slug: 'abacaxi-e-vinagrete', titulo: 'Vinagrete de abacaxi' },
  { slug: 'abacaxi-e-sorbet', titulo: 'Sorbet de abacaxi' },
  { slug: 'abacaxi-e-picolé', titulo: 'Picolé de abacaxi' },
  { slug: 'abacaxi-e-drink-alcoolico', titulo: 'Drink alcoólico com abacaxi' },
  { slug: 'abacaxi-e-mocktail', titulo: 'Mocktail de abacaxi' },
  { slug: 'abacaxi-e-cha', titulo: 'Chá de casca de abacaxi' },
  { slug: 'abacaxi-e-infusao', titulo: 'Infusão de abacaxi' },
  { slug: 'abacaxi-e-agua-saborizada', titulo: 'Água saborizada com abacaxi' },
  { slug: 'abacaxi-e-vitaminas', titulo: 'Vitaminas de abacaxi' },
  { slug: 'abacaxi-e-iogurte-grego', titulo: 'Abacaxi com iogurte grego' },
  { slug: 'abacaxi-e-granola', titulo: 'Abacaxi com granola' },
  { slug: 'abacaxi-e-aveia', titulo: 'Abacaxi com aveia' },
  { slug: 'abacaxi-e-chia', titulo: 'Abacaxi com chia' },
  { slug: 'abacaxi-e-linhaça', titulo: 'Abacaxi com linhaça' },
  { slug: 'abacaxi-e-mel', titulo: 'Abacaxi com mel' },
  { slug: 'abacaxi-e-hortela', titulo: 'Abacaxi com hortelã' },
  { slug: 'abacaxi-e-gengibre', titulo: 'Abacaxi com gengibre' },
  { slug: 'abacaxi-e-limao', titulo: 'Abacaxi com limão' },
  { slug: 'abacaxi-e-laranja', titulo: 'Abacaxi com laranja' },
  { slug: 'abacaxi-e-morango', titulo: 'Abacaxi com morango' },
  { slug: 'abacaxi-e-banana', titulo: 'Abacaxi com banana' },
  { slug: 'abacaxi-e-manga', titulo: 'Abacaxi com manga' },
  { slug: 'abacaxi-e-maracuja', titulo: 'Abacaxi com maracujá' },
  { slug: 'abacaxi-e-kiwi', titulo: 'Abacaxi com kiwi' },
  { slug: 'abacaxi-e-uva', titulo: 'Abacaxi com uva' },
  { slug: 'abacaxi-e-melancia', titulo: 'Abacaxi com melancia' },
  { slug: 'abacaxi-e-mamao', titulo: 'Abacaxi com mamão' },
  { slug: 'abacaxi-e-goiaba', titulo: 'Abacaxi com goiaba' },
  { slug: 'abacaxi-e-pessego', titulo: 'Abacaxi com pêssego' },
  { slug: 'abacaxi-e-ameixa', titulo: 'Abacaxi com ameixa' },
  { slug: 'abacaxi-e-cereja', titulo: 'Abacaxi com cereja' },
  { slug: 'abacaxi-e-framboesa', titulo: 'Abacaxi com framboesa' },
  { slug: 'abacaxi-e-amora', titulo: 'Abacaxi com amora' },
  { slug: 'abacaxi-e-mirtilo', titulo: 'Abacaxi com mirtilo' },
  { slug: 'abacaxi-e-coco-ralado', titulo: 'Abacaxi com coco ralado' },
  { slug: 'abacaxi-e-leite-condensado', titulo: 'Abacaxi com leite condensado' },
  { slug: 'abacaxi-e-creme-de-leite', titulo: 'Abacaxi com creme de leite' },
  { slug: 'abacaxi-e-chantilly', titulo: 'Abacaxi com chantilly' },
  { slug: 'abacaxi-e-chocolate', titulo: 'Abacaxi com chocolate' },
  { slug: 'beneficios-do-abacate', titulo: 'Os incríveis benefícios do abacate para a saúde' },
];
